### ISSUE TITLE
Got issue bro!

### ISSUE THREAD

**Issue by 0xifis** [jethrokuan/gitalias#1]
read: Unknown option 'alias'
/Users/vishthemenon/.local/share/fisherman/functions/fisher.fish (line 2): while read -la alias
                                                                           ^
in function 'fisher',
    called on standard input,
    with parameter list 'uninstall jethrokuan/gitalias'

```
   read − read ‐ read line of input into variables
```

read ‐ read line of input into variables
   Synopsis
       read [OPTIONS] [VARIABLES...]

read: Type 'help read' for related documentation

**Comment by jethrokuan** [comment]
Issue is with fisher. Closing.
